module.exports = {
    GET_HOURS_FOR_DAY: "GetHoursForDay",
    REGISTER_BTN_CLICKED: "RegisterBtnClicked",
    REGISTER_USER: "RegisterUser",
    SIGN_IN_USER: "SignInUser",
    SIGN_OUT_USER: "SignOutUser",
    CLEAR_LOGIN_DATA: "ClearLoginData",
    SET_LOGIN_EMAIL: "SetLoginEmail",
    SET_LOGIN_PASSWORD: "SetLoginPassword",
    CLEAR_REGISTER_DATA: "ClearRegisterData",
    SET_REGISTER_EMAIL: "SetRegisterEmail",
    SET_REGISTER_PASSWORD: "SetRegisterPassword",
    SET_REGISTER_PASSWORD_CONFIRMATION: "SetRegisterPasswordConfirmation",
    SET_REGISTER_NAME: "SetRegisterName",
    SET_REGISTER_COMPANY_NAME: "SetRegisterCompanyName",
    SET_CALENDAR_GRID_DATA: "SetCalendarGridData",
    GET_PLANNER_CALENDAR: "GetPlannerCalendar",
    SET_HOURS_FOR_DAY: "SetHoursForDay",
    SET_NEXT_WEEK_DATES: "SetNextWeekDates",
    SET_CURRENT_WEEK_DATES: "SetCurrentWeekDates",
    SET_PREVIOUS_WEEK_DATES: "SetPreviousWeekDates",
    SET_SELECTED_WEEK_DATES: "SetSelectedWeekDates",
    SET_SELECTED_DATE: "SetSelectedDay",
    STORE_SELECT_WHOLE_WEEK_BY_DAY_IN_CALENDAR: "StoreSelectWholeWeekByDayInCalendar"
}